# Generating a new SSH key in repo after inport project
# mkdir .ssh
# ssh-keygen -f .ssh/id_rsa

stages:
  - deploy

before_script:
  - apt-get update
  - apt-get install -y python-pip openssh-client sshpass git apache2-utils
  - pip install ansible ansible-modules-hashivault kubespray
  - chmod 0600 .ssh/id_rsa
  - eval `ssh-agent`
  - ssh-add .ssh/id_rsa
  - sshpass -p random-password /usr/bin/ssh-copy-id -f -o StrictHostKeyChecking=no user_kuber@ip-node1
  - sshpass -p random-password /usr/bin/ssh-copy-id -f -o StrictHostKeyChecking=no user_kuber@ip-node2
  - sshpass -p random-password /usr/bin/ssh-copy-id -f -o StrictHostKeyChecking=no user_kuber@ip-node3

deploy:
  stage: deploy
  script:
    - echo ip-node1 node1 >> /etc/hosts
    - echo ip-node2 node2 >> /etc/hosts
    - echo ip-node3 node3 >> /etc/hosts
    - mv .kubespray.yml /root
    - kubespray prepare --nodes node1 node2 node3 --etcds 3 --masters 2
    - kubespray deploy --verbose --assumeyes --user user_kuber -i inventory/inventory.cfg --ansible-opts '-e docker_dns_servers_strict=false'
